//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Specification.Expressions {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SpecAbsRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SpecAbsRes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Specification.Expressions.SpecAbsRes", typeof(SpecAbsRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not {0} values for {1}.
        /// </summary>
        internal static string CompareSpecificationNotMatch {
            get {
                return ResourceManager.GetString("CompareSpecificationNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} {1} {2}.
        /// </summary>
        internal static string CompareSpecificationToString {
            get {
                return ResourceManager.GetString("CompareSpecificationToString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum {0} specifications expected.
        /// </summary>
        internal static string CompositeSpecificationMinimum {
            get {
                return ResourceManager.GetString("CompositeSpecificationMinimum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to equal.
        /// </summary>
        internal static string EqualSpecificationName {
            get {
                return ResourceManager.GetString("EqualSpecificationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key {0} is missing.
        /// </summary>
        internal static string KeyValueSpecificationMissingKey {
            get {
                return ResourceManager.GetString("KeyValueSpecificationMissingKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value of type {0} for key {1} can&apos;t be compared with type {2}.
        /// </summary>
        internal static string KeyValueSpecificationTypeNotMatch {
            get {
                return ResourceManager.GetString("KeyValueSpecificationTypeNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value of type {0} for key {1} can&apos;t be converted to {2}.
        /// </summary>
        internal static string KeyValueSpecificationTypeNotSupported {
            get {
                return ResourceManager.GetString("KeyValueSpecificationTypeNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value for key {0} is null.
        /// </summary>
        internal static string KeyValueSpecificationValueNull {
            get {
                return ResourceManager.GetString("KeyValueSpecificationValueNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All of ({0}).
        /// </summary>
        internal static string SpecificationValueAllOf {
            get {
                return ResourceManager.GetString("SpecificationValueAllOf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Any of ({0}).
        /// </summary>
        internal static string SpecificationValueAnyOf {
            get {
                return ResourceManager.GetString("SpecificationValueAnyOf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value of type {0} not supported. List of supported types: {1}.
        /// </summary>
        internal static string SpecificationValueTypeNotSupported {
            get {
                return ResourceManager.GetString("SpecificationValueTypeNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Single value expected, however {0} values were provided.
        /// </summary>
        internal static string ValueSpecification_ValueSpecification_Single_value_expected__however__0__values_were_provided {
            get {
                return ResourceManager.GetString("ValueSpecification_ValueSpecification_Single_value_expected__however__0__values_w" +
                        "ere_provided", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All values should have the same type.
        /// </summary>
        internal static string ValueSpecificationMixedTypes {
            get {
                return ResourceManager.GetString("ValueSpecificationMixedTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Single value expected, however {0} values were provided.
        /// </summary>
        internal static string ValueSpecificationMultipleValuesProvided {
            get {
                return ResourceManager.GetString("ValueSpecificationMultipleValuesProvided", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Null value type not allowed.
        /// </summary>
        internal static string ValueSpecificationNullNotAllowed {
            get {
                return ResourceManager.GetString("ValueSpecificationNullNotAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only {0} multiplicity is allowed for value.
        /// </summary>
        internal static string ValueSpecificationOnlySingleMultiplicity {
            get {
                return ResourceManager.GetString("ValueSpecificationOnlySingleMultiplicity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Values were not provided.
        /// </summary>
        internal static string ValueSpecificationValuesNotProvided {
            get {
                return ResourceManager.GetString("ValueSpecificationValuesNotProvided", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At least one value should be provided.
        /// </summary>
        internal static string ValueSpecificationZeroCount {
            get {
                return ResourceManager.GetString("ValueSpecificationZeroCount", resourceCulture);
            }
        }
    }
}
